# Generated by Django 3.2.4 on 2021-07-05 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0003_auto_20210705_1345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meetup',
            old_name='location',
            new_name='locations',
        ),
    ]
