# Generated by Django 3.2.4 on 2021-07-05 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0004_rename_location_meetup_locations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meetup',
            old_name='locations',
            new_name='location',
        ),
    ]
